SPY = float(input("Enter amount invested in SPY: "))
QQQ = float(input("Enter amount invested in QQQ: "))
EEM = float(input("Enter amount invested in EEM: "))
VXX = float(input("Enter amount invested in VXX: "))
total = SPY + QQQ + EEM + VXX
print()
print("{0:6s}{1:>12s}".format("ETF", "PERCENTAGE"))
print("-" * 18)
print("{0:6s}{1:10.2%}".format("SPY", SPY / total))
print("{0:6s}{1:10.2%}".format("QQQ", QQQ / total))
print("{0:6s}{1:10.2%}".format("EEM", EEM / total))
print("{0:6s}{1:10.2%}".format("VXX", VXX / total))
print()
print("{0:s}{1:,.2f}".format("TOTAL AMOUNT INVESTED: $", total))
